###
POST http://localhost:3000/comments/create
Content-Type: application/json

{
    "contenido": "Comentario 4",
    "post_id": 1,
    "user_id": 1
}

###
POST http://localhost:3000/posts/create/1
Content-Type: application/json

{
  "texto": "Post 3"

}


###
POST http://localhost:3000/users/create
Content-Type: application/json

{
  "nickName": "usuario 1"
}

###
POST http://localhost:3000/tags/create
Content-Type: application/json

{
  "name": "tag 1"
}
###
POST http://localhost:3000/posts/1/create-tag
Content-Type: application/json

{
  "tag_id": 1
}
###
POST http://localhost:3000/post_Images/create
Content-Type: multipart/form-data; boundary=MiBoundaryLoco

--MiBoundaryLoco
Content-Disposition: form-data; name="post_id"

1
--MiBoundaryLoco
Content-Disposition: form-data; name="image"; filename="prueba.jpg"
Content-Type: image/jpeg

< ./assets/ANTI-SOCIALNET.jpeg
--MiBoundaryLoco--

###
GET http://localhost:3000/comments/3
###
GET http://localhost:3000/users/6

###
GET http://localhost:3000/comments/6
###
GET http://localhost:3000/tags/1
###
GET http://localhost:3000/posts/1
###
GET http://localhost:3000/users/1/posts
###
GET http://localhost:3000/posts/1/user

###
GET http://localhost:3000/posts/1/comments
###
GET http://localhost:3000/posts/1/tags

###
DELETE http://localhost:3000/posts/1